[package]
name = "atomic_bitfield"
version = "0.1.0"
authors = ["Amer Safdari <amersafdari@gmail.com>"]
edition = "2018"
license = "MIT"

[features]
default = []
nightly = []

[dependencies]
bit_field = "0.9"
cfg-if = "0.1"
